# ===> Image officielle tensorflow à utiliser
FROM tensorflow/tensorflow:latest-gpu

WORKDIR /app

# ===> Création du répertoire pour sauvegarder le modèle entrainé

RUN mkdir -p /app/modelSaved

# Installation de dépendances/librairies python 
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libopencv-dev \
        python3-opencv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements_trainer.txt /app/
RUN pip install --no-cache-dir -r requirements_trainer.txt

# ===> Copie du script d'entraînement du local vers le working dir du container
COPY modelImages.py /app/

# ===> Command to run the training script
CMD ["python", "modelImages.py"]